name: Deploy Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Server Environment
        working-directory: ./server
        run: |
          npm ci

      - name: Build Server
        working-directory: ./server
        run: npm run build

      - name: Deploy to Render
        run: |
          curl -fsSL https://cli.render.com/install.sh | sh
          render service deploy srv-d0b1b3euk2gs73c9m23g --key aS9sGrfzQKM
        working-directory: ./server
