name: Deploy Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Client Environment
        working-directory: ./client
        run: |
          npm install -g pnpm
          pnpm install

      - name: Setup Server Environment
        working-directory: ./server
        run: |
          npm ci

      - name: Build Server
        working-directory: ./server
        run: npm run build

  deploy-server:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-d0b1b3euk2gs73c9m23g/deploys" \
            -H "Authorization: Bearer rnd_cESLWXSc2vIm38ns8LxbmY2vPzBS" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "do_not_clear"}'
        working-directory: ./server
